version: "3.9"

services:
  manga-notifier:
    build: .
    container_name: manga-notifier
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped