version: "3.9"

services:
  manga-notifier:
    build: .
    container_name: manga-notifier
    env_file:
      - .env
    volumes:
      - manga_db:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  manga_db: